### ISSUE TITLE
Simplify usage

### ISSUE THREAD

**Issue by oddui** [zoogie/new-browserhax#2]
Hello @zoogie ,

I'd like to avoid having to put the region specific `arm11code.bin` and `browserhax_hblauncher_ropbin_payload.bin` files to SD card.

I feel that it's possible to convert the php code in 3ds_browserhax_common to JavaScript code that runs in browsers.
I see that the php code can build `arm11code.bin` into the rop chain. So it should be possible to download `arm11code.bin` using JavaScript then build it into the rop chain. However i'm not sure what is the `browserhax_hblauncher_ropbin_payload.bin` file and where is it from.

Could you explain what `browserhax_hblauncher_ropbin_payload.bin` does and if it is possible to be built into the rop chain just like `arm11code.bin`?

Thank you

**Comment by zoogie** [comment]
I plan on releasing an automated system to download these files in the future. For now, the hacks.guide people are happy with the current setup. You can test my basic auto download version by going to: https://zoogie.github.io/web/auto. My idea is to actually go a step beyond that and download *everything*. (https://zoogie.github.io/web/full -- I don't recommend doing this without instructions though, it's not ready for public use). The reason this stuff isn't officially out yet is because I'm working on higher priorities like full region support and backup browser sploits.

> Could you explain what browserhax_hblauncher_ropbin_payload.bin does and if it is possible to be built into the rop chain just like arm11code.bin?

It's like otherapp.bin, but for browsers. I don't plan on building that into the html, it would be slower and mess up the heap probably.
